# Get this from internet.bs
apiKey: RANDOMCHARACTERS
# Get this from intertnet.bs
password: MORERANDOMCHARACHTERS
# Domain you wish to keep updated to the dynamic ip
domain: home.jmainguy.com
# API url
url: https://api.internet.bs/Domain/DnsRecord/Update

